# Site settings
title: Iglesia Evangélica de Cristo Salvador
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Iglesia Evangélica de Cristo Salvador, Madrid.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  cristosalvador

# Build settings
markdown: kramdown
