# Site settings
title: Iglesia Cristiana Cristo Salvador Madrid
email: contacto@cristomadrid.es
description: "Iglesia Cristo Salvador es una iglesia evangélica de Madrid, descubriendo la gracia de Dios. Somos parte de una familia de iglesias que se llama Commission; Commission es una parte de Newfrontiers."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cristomadrid.es" # the base hostname & protocol for your site
github_username: cristosalvador
twitter_username: madrid_cristo
facebook_username: CristoSalvadorMadrid
images_path: /images
mainimage: /images/hero_final.jpg
js_path: /js
css_path: /css

# Build settings
markdown: kramdown
