# Site settings
title: Iglesia Cristo Salvador Madrid
email: your-email@domain.com
description: Cristo Salvador es una Iglesia Evangélica, unida en una misión para compartir la gracia magnifica de Dios con nuestra ciudad Madrid.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cristomadrid.es" # the base hostname & protocol for your site
github_username:  cristosalvador

images_path: /images
js_path: /js
css_path: /css

# Build settings
markdown: kramdown
