# Site settings
title: Iglesia Cristo Salvador Madrid
email: info@cristomadrid.es
description: "Cristo Salvador Madrid es una Iglesia Cristiana Evangélica, compuesta de gente, en lugar de ladrillos, que ama a Jesús y a Madrid."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cristomadrid.es" # the base hostname & protocol for your site
github_username: cristosalvador
twitter_username: madrid_cristo
facebook_username: CristoSalvadorMadrid
images_path: /images
js_path: /js
css_path: /css

# Build settings
markdown: kramdown
